### ISSUE TITLE
CountryInfo.Countries has a dublicate value for Montenegro

### ISSUE THREAD

**Issue by ChristosAsvestopoulos** [indice-co/Indice.AspNet#129]
Dear Indice Development Team,

I have noticed that CountryInfo.Countries

https://github.com/indice-co/Indice.AspNet/blob/a5dcd2670006f2b3e2b3ec1bd6d4272eb9b173c4/src/Indice.Common/Types/CountryInfo.cs#L40

has a dublicate value for Montenegro:

https://github.com/indice-co/Indice.AspNet/blob/a5dcd2670006f2b3e2b3ec1bd6d4272eb9b173c4/src/Indice.Common/Types/CountryInfo.cs#L189

https://github.com/indice-co/Indice.AspNet/blob/a5dcd2670006f2b3e2b3ec1bd6d4272eb9b173c4/src/Indice.Common/Types/CountryInfo.cs#L241

According to [this](https://www.iso.org/obp/ui/#iso:code:3166:ME) and [this](https://countrycode.org/montenegro) Montenegro's numericCode is 499, its capital is Podgorica and its callingCode is 382.

**Comment by ChristosAsvestopoulos** [comment]
...and the empty space should propably be removed in:
https://github.com/indice-co/Indice.AspNet/blob/a5dcd2670006f2b3e2b3ec1bd6d4272eb9b173c4/src/Indice.Common/Types/CountryInfo.cs#L282

**Comment by cleftheris** [comment]
According to google the other one is actually Serbia (already existing) so please add a pull request to delete it. And find it in the excel file too and remove the duplicate record there too.
```csharp
{ new CountryInfo("EU", "ME", "MNE", 891, "Serbia", "Belgrade", "cu,hu,sq,sr", "381") }, 
```


https://www.google.com/search?q=calling+code+381&oq=calling+code+381&aqs=edge..69i57j0i22i30l5j0i15i22i30l3.3612j0j1&sourceid=chrome&ie=UTF-8
