### ISSUE TITLE
Make PhoneNumber RegEx configurable

### ISSUE THREAD

**Issue by dkarkanas** [indice-co/Indice.AspNet#221]
# Description 
The "update phone number" api endpoint has a regex hardcoded. This must be configured from the Consumer

https://github.com/indice-co/Indice.AspNet/blob/develop/src/Indice.Features.Identity.Server/Manager/Models/Requests/UpdateUserPhoneNumberRequest.cs

We need to keep in mind all the corresponding phone-update actions (eg from AdminUI or IdentityMvc)

**Comment by cleftheris** [comment]
As of this https://github.com/indice-co/Indice.AspNet/commit/8d2c9242d6f3d1446c69072692b80a5379e1262b 
Later versions have this feature configurable through setting

@Sorras-Panagiotis Please update this issue with more info about the settings needed

**Comment by Sorras-Panagiotis** [comment]
For mobile phones, there is the possibility to set the control for the format of the mobile. This setting can be used in scenarios where there is a need for the system to support mobiles that are not in Greek format (69x xxx xxxx).
The setting is optional. If not used, validation for Greek mobiles appears.

IdentityOptions:User:PhoneNumberRegex: regex string
IdentityOptions:User:PhoneNumberRegexMessage: string | Default Value: "The field '{PropertyName}' has invalid format.

cc @cleftheris @dkarkanas
