### ISSUE TITLE
IAM: Remove unlock button for roles without user edit permissions

### ISSUE THREAD

**Issue by perisdr** [indice-co/Indice.AspNet#481]
**Description:**
As a Backoffice user without permissions to edit users, I observed unexpected behavior when interacting with the unlock button on a locked user's details page. Clicking the unlock button causes the informative banner to disappear, even though the action fails under the hood with a 403 error.

**Steps to Reproduce:**
1. Log in as a Backoffice user without user edit permissions.
2. Navigate to the details page of a locked user.
3. Observe the informative banner displayed along with the unlock button.
4. Click the unlock button.

**Expected Behavior:**
- The banner should remain visible.
- An appropriate error message should inform the user that the unlock action failed due to insufficient permissions.

**Actual Behavior:**
- The banner disappears.
- No feedback is provided to the user.
- A 403 error is logged under the hood, indicating that the unlock action was unauthorized.

**Environment:**
- IAM Version: `v7.34.0`
- User Role: Backoffice user without user edit permissions

**Additional Information:**
- This issue may cause confusion for users as the disappearing banner could imply that the unlock action was successful.

**Log output:**
- [ERROR] 403 Unauthorized

**Suggested Fix:**
- Prevent the banner from disappearing unless the unlock action is successfully completed.
- Hide the unlock button when the BackOffice Agent lacks user edit permissions.
- Display a clear error message to the user when the unlock action fails due to insufficient permissions.

**Impact:**
This issue creates a misleading user experience and may result in unnecessary support tickets or confusion among Backoffice users.

![image](https://github.com/user-attachments/assets/ae934900-829a-47d5-9fed-8ca3e93f2b0f)
![image](https://github.com/user-attachments/assets/a6f2caf8-451c-48b8-8df3-7736cd9dc867)

**Comment by cleftheris** [comment]
The user seems to be a reader in role. The fix should be 
1. first handle the 403 with an error toast notification if the UI engineer has not considered hiding a button when a user has not the right privilidges for an action. 
2. Make the button available only to Admin, UserWriter, UserAdministrator, Administrator

**Comment by cleftheris** [comment]
@perisdr When reporting a bug please state the version number of the Identity system (preferably server & adminUI)

**Comment by perisdr** [comment]
@cleftheris the IAM Version: v7.34.0 I wrote in the issue refers to the adminUI? I assume for the server I need to ask an engineer for the nuget package?

**Comment by cleftheris** [comment]
It is hidden in the footer in an element right beside the privacy policy link
![Screenshot 2024-12-13 105503](https://github.com/user-attachments/assets/b8993355-59b9-48f1-b19f-278051a91a97)
![Screenshot 2024-12-13 105544](https://github.com/user-attachments/assets/2793d961-ffdb-45cb-9e88-e2e0e33dafbd)

**Comment by cleftheris** [comment]
The class is misspelled as a testament that I have written the code for it. 🤣
