### ISSUE TITLE
FileServiceAzure GetProperties Etag Quotes missing since Azure.Storage.Blob v12.9.0+

### ISSUE THREAD

**Issue by vaggelanos** [indice-co/Indice.AspNet#52]
@giorgos07 
Keep this issue open until its fixed and published by Azure team.
After that we will remove the workaround code and close the issue
https://github.com/Azure/azure-sdk-for-net/issues/22877

**Comment by cleftheris** [comment]
@giorgos07 can u relaese a version of the packages please. We got a workaround in  #53
